image: alpine

before_script:
  - apk add --no-cache openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PK_GR" | tr -d '\r' > id_rsa
  - chmod 600 id_rsa
  - cat -A id_rsa
  - ssh-add id_rsa
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - touch ~/.ssh/known_hosts
  - ssh-keyscan login6.informatik.uni-wuerzburg.de >> ~/.ssh/known_hosts
  - ssh-keyscan slurmmaster-ls6 >> ~/.ssh/known_hosts

stages:
  - update-repo

update-repo:
  stage: update-repo
  only:
    - main
  script:
    - ssh -o ProxyJump=login6.informatik.uni-wuerzburg.de hauptmann@slurmmaster-ls6 "cd /home/ls6/hauptmann/ethikchat-experiment-argument-classification && git pull origin main"
